### ISSUE TITLE
File names - Issue with 'Save as PDF' functionality

### ISSUE THREAD

**Issue by katetaylormoz** [Mozilla-Ocho/Memory-Cache#52] opened 2024-01-23 17:53 UTC
**Issue:**
File name defaults to 'PAGE-[object Promise]' for every PDF saved

**Preferred Behaviour (or similar):**
PAGE-Carl-Sagan---Wikiquote-2024-01-23.html
PAGE-Carl-Sagan---Wikiquote-2024-01-23.pdf

**Notes:**
Priority is human-readable filename, 
Nice-To-Have would be html and pdf are the same name with different formats

**Comment by bharattech** [comment] 2024-01-24 06:06
Hi @katetaylormoz ,

In the past, I have worked on  #Make file names more readable #10 , which has equipped me with the necessary skills and knowledge to address the challenges posed by this particular issue.

I would be grateful if you could consider assigning this issue to me. I am committed to delivering high-quality solutions and collaborating closely with the team to ensure the successful resolution of the problem.

If there are any specific steps or additional information required from my side, please let me know. I understand that your time is valuable, and I appreciate your consideration of my request.

Best regards,
Bharat

**Comment by bharattech** [comment] 2024-01-24 06:15
@katetaylormoz , I attempted to replicate the reported issue on my local environment, but regrettably, I was unable to reproduce it. I would appreciate your guidance in helping me understand the factors causing the issue.

![Screenshot from 2024-01-24 11-39-03](https://github.com/Mozilla-Ocho/Memory-Cache/assets/60472110/9c6d44a3-2465-4f34-96c5-8d5416fc7ad6)

**Comment by bharattech** [comment] 2024-01-24 15:52
Hi @katetaylormoz ,

Thanks for the info.

I am able to reproduce this issue in Firefox browser.

It appears that step 3 from the Prerequisites section has been overlooked

https://github.com/Mozilla-Ocho/Memory-Cache

You need to use Firefox from https://github.com/Mozilla-Ocho/Memory-Cache/wiki/Modifying-Firefox-to-Save-PDF-files-automagically-to-MemoryCache

Kindly proceed with the given steps, and don't hesitate to contact me if you need any help.

Regards
Bharat

**Comment by katetaylormoz** [comment] 2024-01-24 18:24
Ah, I see. I have been trying to avoid using a source-build of Firefox. This explains the issue though

**Comment by bharattech** [comment] 2024-01-25 04:34
I would like to kindly request the closure of this issue.
If there are any additional steps or information required from my end, please let me know.

**Closed** 2024-01-25 13:44 UTC
